### ISSUE TITLE
404 on tracing module (API)

### ISSUE THREAD

**Issue by paulomcnally** [nodejs/nodejs.org-archive#77] opened 2015-02-09 03:22 UTC
http://nodejs.org/api/tracing.html

**Comment by robertkowalski** [comment] 2015-02-09 18:48
good catch! i opened a PR to adress the problem

**Comment by misterdjules** [comment] 2015-02-24 19:26
@robertkowalski I don't see in this repository the PR you mention, and the problem seems to not be fixed. Could you please create it so that we can merge it and fix this issue?

Thanks!

**Comment by robertkowalski** [comment] 2015-02-24 19:30
yes @paulomcnally closed the issue 

still waiting for a review on https://github.com/joyent/node/pull/9172 - PTAL :)

**Comment by paulomcnally** [comment] 2015-02-24 19:36
@misterdjules moved to: https://github.com/joyent/node/pull/9172

**Comment by misterdjules** [comment] 2015-02-24 19:44
@robertkowalski Found it: joyent/node#9172.

**Comment by misterdjules** [comment] 2015-02-24 19:55
@paulomcnally Thanks :)

The fix landed in https://github.com/joyent/node/commit/08a1192478ed84422902d59a8bfe056ff88cc88d. With this fix and following our usual workflow, the API doc's table of content would be updated when node v0.12.1 is released. I would like to deploy this fix sooner than that though, as we still don't know when this release will happen.

@tjfontaine @robertkowalski It should be safe to `rsync -r out/doc/ node@nodejs.org:~/web/nodejs.org/` right?

**Comment by misterdjules** [comment] 2015-02-24 22:26
I deployed https://github.com/joyent/node/commit/08a1192478ed84422902d59a8bfe056ff88cc88d to nodejs.org to avoid having to wait for v0.12.1 to fix this annoying and confusing issue.

I cherry-picked https://github.com/joyent/node/commit/08a1192478ed84422902d59a8bfe056ff88cc88d and diffed the content of the generated api doc, and then ran `rsync --dry-run` to check which files would be changed. The only change were in the table of content, so I made the decision it was safe to deploy. More details in [this gist](https://gist.github.com/misterdjules/46e8123a9e6097c117c1).

Closing as the TOC at http://nodejs.org/api/ now does not include the tracing module anymore.

Thank you @paulomcnally  and @robertkowalski!

**Comment by paulomcnally** [comment] 2015-03-14 19:57
I use this url to create local documentation https://github.com/nodenica/grunt-node-api-docs-responsive

https://nodejs.org/dist/v0.12.0/docs/api/index.json

tracing link exists on this source :/

**Comment by robertkowalski** [comment] 2015-03-14 19:58
@misterdjules did you port it to 0.12 ?

**Comment by misterdjules** [comment] 2015-03-14 23:01
The fix has been merged into the v0.12 branch, but not into the v0.12.0-release branch. Thus, it's been deployed to `http://nodejs.org/api/`, but not to `http://nodejs.org/dist/v0.12.0/docs/api`.

The v0.12.0 release's artifacts should in my opinion remain intact, and the fix will be present in all subsequent v0.12.x releases.

@paulomcnally Is there a way for you to handle this issue for v0.12.0 in your application?

**Comment by paulomcnally** [comment] 2015-03-14 23:05
Yes @misterdjules for this version (only for this version) i use /api/index.json and not /dist/v0.12.0/docs/api/index.json.

**Comment by misterdjules** [comment] 2015-03-14 23:10
@paulomcnally `/api/index.json` will change and will even eventually not point to a v0.12.x version, so you might want to handle this differently.

**Comment by paulomcnally** [comment] 2015-03-14 23:17
@misterdjules /api/index.json now it's for my custom app. The module use http://nodejs.org/dist/v0.12.0/docs/api/index.json

This solved on next version. From now create a tracing.html empty.

**Comment by misterdjules** [comment] 2015-03-25 18:45
The problem is still present in http://nodejs.org/dist/v0.12.1/docs/api/ because the v0.12.1 release was branched off v0.12.0 and just added the OpenSSL upgrade, thus not including https://github.com/joyent/node/commit/08a1192478ed84422902d59a8bfe056ff88cc88d.

http://nodejs.org/dist/v0.12.2/docs/api/ will definitely not have this problem, sorry for the inconvenience.

**Comment by paulomcnally** [comment] 2015-03-25 18:56
i know :/

Thanks @misterdjules

**Closed as completed** 2015-04-22 20:13 UTC
