### ISSUE TITLE
Broken links to API docs

### ISSUE THREAD

**Issue by disharmonized** [nodejs/nodejs.org-archive#173] opened 2015-09-10 07:16 UTC
All old links to api docs like http://nodejs.org/docs/latest/api/globals.html#globals_dirname
now refer to https://nodejs.org/en/blog/#globals_dirname but should refer to https://nodejs.org/api/globals.html#globals_dirname

**Comment by fhemberger** [comment] 2015-09-10 08:14
Duplicate of https://github.com/nodejs/new.nodejs.org/issues/124

**Closed as completed by fhemberger** 2015-09-10 08:14 UTC

**Comment by rvagg** [comment] 2015-09-10 09:47
fixed, sorry
